const commonWords = [
      "as",
      "wrong",
      "his",
      "that",
      "he",
      "was",
      "for",
      "on",
      "are",
      "with",
      "they",
      "be",
      "at",
      "one",
      "have",
      "this",
      "from",
      "by",
      "hot",
      "word",
      "but",
      "what",
      "some",
      "is",
      "it",
      "you",
      "or",
      "had",
      "the",
      "of",
      "to",
      "and",
      "in",
      "we",
      "can",
      "out",
      "other",
      "were",
      "which",
      "do",
      "their",
      "time",
      "if",
      "will",
      "how",
      "said",
      "an",
      "each",
      "tell",
      "does",
      "set",
      "three",
      "want",
      "air",
      "well",
      "also",
      "play",
      "small",
      "end",
      "put",
      "home",
      "read",
      "hand",
      "port",
      "large",
      "spell",
      "add",
      "even",
      "land",
      "here",
      "must",
      "big",
      "high",
      "such",
      "follow",
      "act",
      "why",
      "ask",
      "men",
      "change",
      "went",
      "light",
      "kind",
      "off",
      "need",
      "house",
      "picture",
      "try",
      "us",
      "again",
      "animal",
      "point",
      "mother",
      "world",
      "near",
      "build",
      "self",
      "earth",
      "father",
      "any",
      "new",
      "work",
      "part",
      "take",
      "get",
      "place",
      "made",
      "live",
      "where",
      "after",
      "back",
      "little",
      "only",
      "round",
      "man",
      "year",
      "came",
      "show",
      "every",
      "good",
      "me",
      "give",
      "our",
      "under",
      "name",
      "very",
      "through",
      "just",
      "form",
      "sentence",
      "great",
      "think",
      "say",
      "help",
      "low",
      "line",
      "differ",
      "turn",
      "cause",
      "much",
      "mean",
      "before",
      "move",
      "right",
      "boy",
      "old",
      "too",
      "same",
      "she",
      "all",
      "there",
      "when",
      "up",
      "use",
      "your",
      "way",
      "about",
      "many",
      "then",
      "them",
      "write",
      "would",
      "like",
      "so",
      "these",
      "her",
      "long",
      "make",
      "thing",
      "see",
      "him",
      "two",
      "has",
      "look",
      "more",
      "day",
      "could",
      "go",
      "come",
      "did",
      "number",
      "sound",
      "no",
      "most",
      "people",
      "my",
      "over",
      "know",
      "water",
      "than",
      "call",
      "first",
      "who",
      "may",
      "down",
      "side",
      "been",
      "now",
      "find",
      "head",
      "stand",
      "own",
      "page",
      "should",
      "country",
      "found",
      "answer",
      "school",
      "grow",
      "study",
      "still",
      "learn",
      "plant",
      "cover",
      "food",
      "sun",
      "four",
      "between",
      "state",
      "keep",
      "eye",
      "never",
      "last",
      "let",
      "thought",
      "city",
      "tree",
      "cross",
      "farm",
      "hard",
      "start",
      "might",
      "story",
      "saw",
      "far",
      "sea",
      "draw",
      "left",
      "late",
      "run",
      "dont",
      "while",
      "press",
      "close",
      "night",
      "real",
      "life",
      "few",
      "north",
      "book",
      "carry",
      "took",
      "science",
      "eat",
      "room",
      "friend",
      "began",
      "idea",
      "fish",
      "mountain",
      "stop",
      "once",
      "base",
      "hear",
      "horse",
      "cut",
      "sure",
      "watch",
      "color",
      "face",
      "wood",
      "main",
      "open",
      "seem",
      "together",
      "next",
      "white",
      "children",
      "begin",
      "got",
      "walk",
      "example",
      "ease",
      "paper",
      "group",
      "always",
      "music",
      "those",
      "both",
      "mark",
      "often",
      "letter",
      "until",
      "mile",
      "river",
      "car",
      "feet",
      "care",
      "second",
      "enough",
      "85",
      "70",
      "26",
      "49",
      "31",
      "94",
      "36",
      "58",
      "10",
      "27",
      "182",
      "693",
      "547",
      "476",
      "319",
      "208",
      "706",
      "543",
      "928",
      "134",
      "7036",
      "2518",
      "9485",
      "2173",
      "9460",
      "9134",
      "8072",
      "6580",
      "2693",
      "4715",
      "~",
      "@",
      "#",
      "$",
      "%",
      "^",
      "&",
      "*",
      "(",
      ")",
      "_",
      "+",
      "{",
      "}",
      "|",
      ":",
      '"',
      "?",
      ">",
      "<",
];
const javascript = [
      "this",
      "function",
      "if",
      "var",
      "return",
      "the",
      "i",
      "a",
      "to",
      "value",
      "else",
      "for",
      "true",
      "length",
      "data",
      "false",
      "name",
      "null",
      "options",
      "is",
      "type",
      "of",
      "param",
      "in",
      "new",
      "element",
      "s",
      "e",
      "event",
      "and",
      "object",
      "prototype",
      "x",
      "jQuery",
      "that",
      "t",
      "key",
      "id",
      "The",
      "string",
      "self",
      "elem",
      "node",
      "on",
      "be",
      "n",
      "b",
      "index",
      "case",
      "d",
      "result",
      "callback",
      "it",
      "undefined",
      "require",
      "y",
      "obj",
      "document",
      "module",
      "from",
      "push",
      "not",
      "or",
      "c",
      "call",
      "typeof",
      "an",
      "_",
      "text",
      "exports",
      "method",
      "width",
      "with",
      "div",
      "use",
      "target",
      "break",
      "get",
      "state",
      "array",
      "set",
      "Object",
      "style",
      "context",
      "scope",
      "error",
      "input",
      "height",
      "arguments",
      "window",
      "p",
      "left",
      "test",
      "val",
      "fn",
      "we",
      "default",
      "o",
      "el",
      "item",
      "number",
      "start",
      "as",
      "path",
      "top",
      "j",
      "class",
      "Math",
      "url",
];

const allWords = [
      "as",
      "i",
      "his",
      "that",
      "he",
      "was",
      "for",
      "on",
      "are",
      "with",
      "they",
      "be",
      "at",
      "one",
      "have",
      "this",
      "from",
      "by",
      "hot",
      "word",
      "but",
      "what",
      "some",
      "is",
      "it",
      "you",
      "or",
      "had",
      "the",
      "of",
      "to",
      "and",
      "in",
      "we",
      "can",
      "out",
      "other",
      "were",
      "which",
      "do",
      "their",
      "time",
      "if",
      "will",
      "how",
      "said",
      "an",
      "each",
      "tell",
      "does",
      "set",
      "three",
      "want",
      "air",
      "well",
      "also",
      "play",
      "small",
      "end",
      "put",
      "home",
      "read",
      "hand",
      "port",
      "large",
      "spell",
      "add",
      "even",
      "land",
      "here",
      "must",
      "big",
      "high",
      "such",
      "follow",
      "act",
      "why",
      "ask",
      "men",
      "change",
      "went",
      "light",
      "kind",
      "off",
      "need",
      "house",
      "picture",
      "try",
      "us",
      "again",
      "animal",
      "point",
      "mother",
      "world",
      "near",
      "build",
      "self",
      "earth",
      "father",
      "any",
      "new",
      "work",
      "part",
      "take",
      "get",
      "place",
      "made",
      "live",
      "where",
      "after",
      "back",
      "little",
      "only",
      "round",
      "man",
      "year",
      "came",
      "show",
      "every",
      "good",
      "me",
      "give",
      "our",
      "under",
      "name",
      "very",
      "through",
      "just",
      "form",
      "sentence",
      "great",
      "think",
      "say",
      "help",
      "low",
      "line",
      "differ",
      "turn",
      "cause",
      "much",
      "mean",
      "before",
      "move",
      "right",
      "boy",
      "old",
      "too",
      "same",
      "she",
      "all",
      "there",
      "when",
      "up",
      "use",
      "your",
      "way",
      "about",
      "many",
      "then",
      "them",
      "write",
      "would",
      "like",
      "so",
      "these",
      "her",
      "long",
      "make",
      "thing",
      "see",
      "him",
      "two",
      "has",
      "look",
      "more",
      "day",
      "could",
      "go",
      "come",
      "did",
      "number",
      "sound",
      "no",
      "most",
      "people",
      "my",
      "over",
      "know",
      "water",
      "than",
      "call",
      "first",
      "who",
      "may",
      "down",
      "side",
      "been",
      "now",
      "find",
      "head",
      "stand",
      "own",
      "page",
      "should",
      "country",
      "found",
      "answer",
      "school",
      "grow",
      "study",
      "still",
      "learn",
      "plant",
      "cover",
      "food",
      "sun",
      "four",
      "between",
      "state",
      "keep",
      "eye",
      "never",
      "last",
      "let",
      "thought",
      "city",
      "tree",
      "cross",
      "farm",
      "hard",
      "start",
      "might",
      "story",
      "saw",
      "far",
      "sea",
      "draw",
      "left",
      "late",
      "run",
      "don’t",
      "while",
      "press",
      "close",
      "night",
      "real",
      "life",
      "few",
      "north",
      "book",
      "carry",
      "took",
      "science",
      "eat",
      "room",
      "friend",
      "began",
      "idea",
      "fish",
      "mountain",
      "stop",
      "once",
      "base",
      "hear",
      "horse",
      "cut",
      "sure",
      "watch",
      "color",
      "face",
      "wood",
      "main",
      "open",
      "seem",
      "together",
      "next",
      "white",
      "children",
      "begin",
      "got",
      "walk",
      "example",
      "ease",
      "paper",
      "group",
      "always",
      "music",
      "those",
      "both",
      "mark",
      "often",
      "letter",
      "until",
      "mile",
      "river",
      "car",
      "feet",
      "care",
      "second",
      "enough",
      "plain",
      "girl",
      "usual",
      "young",
      "ready",
      "above",
      "ever",
      "red",
      "list",
      "though",
      "feel",
      "talk",
      "bird",
      "soon",
      "body",
      "dog",
      "family",
      "direct",
      "pose",
      "leave",
      "song",
      "measure",
      "door",
      "product",
      "black",
      "short",
      "numeral",
      "class",
      "wind",
      "question",
      "happen",
      "complete",
      "ship",
      "area",
      "half",
      "rock",
      "order",
      "fire",
      "south",
      "problem",
      "piece",
      "told",
      "knew",
      "pass",
      "since",
      "top",
      "whole",
      "king",
      "street",
      "inch",
      "multiply",
      "nothing",
      "course",
      "stay",
      "wheel",
      "full",
      "force",
      "blue",
      "object",
      "decide",
      "surface",
      "deep",
      "moon",
      "island",
      "foot",
      "system",
      "busy",
      "test",
      "record",
      "boat",
      "common",
      "gold",
      "possible",
      "plane",
      "stead",
      "dry",
      "wonder",
      "laugh",
      "thousand",
      "ago",
      "ran",
      "check",
      "game",
      "shape",
      "equate",
      "hot",
      "miss",
      "brought",
      "heat",
      "snow",
      "tire",
      "bring",
      "yes",
      "distant",
      "fill",
      "east",
      "paint",
      "language",
      "among",
      "unit",
      "power",
      "town",
      "fine",
      "certain",
      "fly",
      "fall",
      "lead",
      "cry",
      "dark",
      "machine",
      "note",
      "wait",
      "plan",
      "figure",
      "star",
      "box",
      "noun",
      "field",
      "rest",
      "correct",
      "able",
      "pound",
      "done",
      "beauty",
      "drive",
      "stood",
      "contain",
      "front",
      "teach",
      "week",
      "final",
      "gave",
      "green",
      "oh",
      "quick",
      "develop",
      "ocean",
      "warm",
      "free",
      "minute",
      "strong",
      "special",
      "mind",
      "behind",
      "clear",
      "tail",
      "produce",
      "fact",
      "space",
      "heard",
      "best",
      "hour",
      "better",
      "true",
      "during",
      "hundred",
      "five",
      "remember",
      "step",
      "early",
      "hold",
      "west",
      "ground",
      "interest",
      "reach",
      "fast",
      "verb",
      "sing",
      "listen",
      "six",
      "table",
      "travel",
      "less",
      "morning",
      "ten",
      "simple",
      "several",
      "vowel",
      "toward",
      "war",
      "lay",
      "against",
      "pattern",
      "slow",
      "center",
      "love",
      "person",
      "money",
      "serve",
      "appear",
      "road",
      "map",
      "rain",
      "rule",
      "govern",
      "pull",
      "cold",
      "notice",
      "voice",
      "energy",
      "hunt",
      "probable",
      "bed",
      "brother",
      "egg",
      "ride",
      "cell",
      "believe",
      "perhaps",
      "pick",
      "sudden",
      "count",
      "square",
      "reason",
      "length",
      "represent",
      "art",
      "subject",
      "region",
      "size",
      "vary",
      "settle",
      "speak",
      "weight",
      "general",
      "ice",
      "matter",
      "circle",
      "pair",
      "include",
      "divide",
      "syllable",
      "felt",
      "grand",
      "ball",
      "yet",
      "wave",
      "drop",
      "heart",
      "am",
      "present",
      "heavy",
      "dance",
      "engine",
      "position",
      "arm",
      "wide",
      "sail",
      "material",
      "fraction",
      "forest",
      "sit",
      "race",
      "window",
      "store",
      "summer",
      "train",
      "sleep",
      "prove",
      "lone",
      "leg",
      "exercise",
      "wall",
      "catch",
      "mount",
      "wish",
      "sky",
      "board",
      "joy",
      "winter",
      "sat",
      "written",
      "wild",
      "instrument",
      "kept",
      "glass",
      "grass",
      "cow",
      "job",
      "edge",
      "sign",
      "visit",
      "past",
      "soft",
      "fun",
      "bright",
      "gas",
      "weather",
      "month",
      "million",
      "bear",
      "finish",
      "happy",
      "hope",
      "flower",
      "clothe",
      "strange",
      "gone",
      "trade",
      "melody",
      "trip",
      "office",
      "receive",
      "row",
      "mouth",
      "exact",
      "symbol",
      "die",
      "least",
      "trouble",
      "shout",
      "except",
      "wrote",
      "seed",
      "tone",
      "join",
      "suggest",
      "clean",
      "break",
      "lady",
      "yard",
      "rise",
      "bad",
      "blow",
      "oil",
      "blood",
      "touch",
      "grew",
      "cent",
      "mix",
      "team",
      "wire",
      "cost",
      "lost",
      "brown",
      "wear",
      "garden",
      "equal",
      "sent",
      "choose",
      "fell",
      "fit",
      "flow",
      "fair",
      "bank",
      "collect",
      "save",
      "control",
      "decimal",
      "ear",
      "else",
      "quite",
      "broke",
      "case",
      "middle",
      "kill",
      "son",
      "lake",
      "moment",
      "scale",
      "loud",
      "spring",
      "observe",
      "child",
      "straight",
      "consonant",
      "nation",
      "dictionary",
      "milk",
      "speed",
      "method",
      "organ",
      "pay",
      "age",
      "section",
      "dress",
      "cloud",
      "surprise",
      "quiet",
      "stone",
      "tiny",
      "climb",
      "cool",
      "design",
      "poor",
      "lot",
      "experiment",
      "bottom",
      "key",
      "iron",
      "single",
      "stick",
      "flat",
      "twenty",
      "skin",
      "smile",
      "crease",
      "hole",
      "jump",
      "baby",
      "eight",
      "village",
      "meet",
      "root",
      "buy",
      "raise",
      "solve",
      "metal",
      "whether",
      "push",
      "seven",
      "paragraph",
      "third",
      "shall",
      "held",
      "hair",
      "describe",
      "cook",
      "floor",
      "either",
      "result",
      "burn",
      "hill",
      "safe",
      "cat",
      "century",
      "consider",
      "law",
      "bit",
      "coast",
      "copy",
      "phrase",
      "silent",
      "tall",
      "sand",
      "soil",
      "roll",
      "temperature",
      "finger",
      "industry",
      "value",
      "fight",
      "lie",
      "beat",
      "excite",
      "natural",
      "view",
      "sense",
      "capital",
      "won’t",
      "chair",
      "danger",
      "fruit",
      "rich",
      "thick",
      "soldier",
      "process",
      "operate",
      "practice",
      "separate",
      "difficult",
      "doctor",
      "please",
      "protect",
      "noon",
      "crop",
      "modern",
      "element",
      "hit",
      "student",
      "corner",
      "party",
      "supply",
      "whose",
      "locate",
      "ring",
      "character",
      "insect",
      "caught",
      "period",
      "indicate",
      "radio",
      "spoke",
      "atom",
      "human",
      "history",
      "effect",
      "electric",
      "expect",
      "bone",
      "rail",
      "imagine",
      "provide",
      "agree",
      "thus",
      "gentle",
      "woman",
      "captain",
      "guess",
      "necessary",
      "sharp",
      "wing",
      "create",
      "neighbor",
      "wash",
      "bat",
      "rather",
      "crowd",
      "corn",
      "compare",
      "poem",
      "string",
      "bell",
      "depend",
      "meat",
      "rub",
      "tube",
      "famous",
      "dollar",
      "stream",
      "fear",
      "sight",
      "thin",
      "triangle",
      "planet",
      "hurry",
      "chief",
      "colony",
      "clock",
      "mine",
      "tie",
      "enter",
      "major",
      "fresh",
      "search",
      "send",
      "yellow",
      "gun",
      "allow",
      "print",
      "dead",
      "spot",
      "desert",
      "suit",
      "current",
      "lift",
      "rose",
      "arrive",
      "master",
      "track",
      "parent",
      "shore",
      "division",
      "sheet",
      "substance",
      "favor",
      "connect",
      "post",
      "spend",
      "chord",
      "fat",
      "glad",
      "original",
      "share",
      "station",
      "dad",
      "bread",
      "charge",
      "proper",
      "bar",
      "offer",
      "segment",
      "slave",
      "duck",
      "instant",
      "market",
      "degree",
      "populate",
      "chick",
      "dear",
      "enemy",
      "reply",
      "drink",
      "occur",
      "support",
      "speech",
      "nature",
      "range",
      "steam",
      "motion",
      "path",
      "liquid",
      "log",
      "meant",
      "quotient",
      "teeth",
      "shell",
      "neck",
      "oxygen",
      "sugar",
      "death",
      "pretty",
      "skill",
      "women",
      "season",
      "solution",
      "magnet",
      "silver",
      "thank",
      "branch",
      "match",
      "suffix",
      "especially",
      "fig",
      "afraid",
      "huge",
      "sister",
      "steel",
      "discuss",
      "forward",
      "similar",
      "guide",
      "experience",
      "score",
      "apple",
      "bought",
      "led",
      "pitch",
      "coat",
      "mass",
      "card",
      "band",
      "rope",
      "slip",
      "win",
      "dream",
      "evening",
      "condition",
      "feed",
      "tool",
      "total",
      "basic",
      "smell",
      "valley",
      "nor",
      "double",
      "seat",
      "continue",
      "block",
      "chart",
      "hat",
      "sell",
      "success",
      "company",
      "subtract",
      "event",
      "particular",
      "deal",
      "swim",
      "term",
      "opposite",
      "wife",
      "shoe",
      "shoulder",
      "spread",
      "arrange",
      "camp",
      "invent",
      "cotton",
      "born",
      "determine",
      "quart",
      "nine",
      "truck",
      "noise",
      "level",
      "chance",
      "gather",
      "shop",
      "stretch",
      "throw",
      "shine",
      "property",
      "column",
      "molecule",
      "select",
      "gray",
      "repeat",
      "require",
      "broad",
      "prepare",
      "salt",
      "nose",
      "plural",
      "anger",
      "claim",
      "continent",
];

const mongoose = require("mongoose");
mongoose
      .connect("mongodb://127.0.0.1:27017/typing")
      .then(() => {
            console.log("connected to mongodb");
      })
      .catch((e) => {
            console.log(e);
      });
// const commonWordsModel = require("./models/commonWordsModel");
const wordsModel = require("./models/wordsModel");

// const data = {
//       commonWords: [
//             "a",
//             "able",
//             "about",
//             "absolute",
//             "accept",
//             "account",
//             "achieve",
//             "across",
//             "act",
//             "active",
//             "actual",
//             "add",
//             "address",
//             "admit",
//             "advertise",
//             "affect",
//             "afford",
//             "after",
//             "afternoon",
//             "again",
//             "against",
//             "age",
//             "agent",
//             "ago",
//             "agree",
//             "air",
//             "all",
//             "allow",
//             "almost",
//             "along",
//             "already",
//             "alright",
//             "also",
//             "although",
//             "always",
//             "america",
//             "amount",
//             "and",
//             "another",
//             "answer",
//             "any",
//             "apart",
//             "apparent",
//             "appear",
//             "apply",
//             "appoint",
//             "approach",
//             "appropriate",
//             "area",
//             "argue",
//             "arm",
//             "around",
//             "arrange",
//             "art",
//             "as",
//             "ask",
//             "associate",
//             "assume",
//             "at",
//             "attend",
//             "authority",
//             "available",
//             "aware",
//             "away",
//             "awful",
//             "baby",
//             "back",
//             "bad",
//             "bag",
//             "balance",
//             "ball",
//             "bank",
//             "bar",
//             "base",
//             "basis",
//             "be",
//             "bear",
//             "beat",
//             "beauty",
//             "because",
//             "become",
//             "bed",
//             "before",
//             "begin",
//             "behind",
//             "believe",
//             "benefit",
//             "best",
//             "bet",
//             "between",
//             "big",
//             "bill",
//             "birth",
//             "bit",
//             "black",
//             "bloke",
//             "blood",
//             "blow",
//             "blue",
//             "board",
//             "boat",
//             "body",
//             "book",
//             "both",
//             "bother",
//             "bottle",
//             "bottom",
//             "box",
//             "boy",
//             "break",
//             "brief",
//             "brilliant",
//             "bring",
//             "britain",
//             "brother",
//             "budget",
//             "build",
//             "bus",
//             "business",
//             "busy",
//             "but",
//             "buy",
//             "by",
//             "cake",
//             "call",
//             "can",
//             "car",
//             "card",
//             "care",
//             "carry",
//             "case",
//             "cat",
//             "catch",
//             "cause",
//             "cent",
//             "centre",
//             "certain",
//             "chair",
//             "chairman",
//             "chance",
//             "change",
//             "chap",
//             "character",
//             "charge",
//             "cheap",
//             "check",
//             "child",
//             "choice",
//             "choose",
//             "Christ",
//             "Christmas",
//             "church",
//             "city",
//             "claim",
//             "class",
//             "clean",
//             "clear",
//             "client",
//             "clock",
//             "close",
//             "closes",
//             "clothe",
//             "club",
//             "coffee",
//             "cold",
//             "colleague",
//             "collect",
//             "college",
//             "colour",
//             "come",
//             "comment",
//             "commit",
//             "committee",
//             "common",
//             "community",
//             "company",
//             "compare",
//             "complete",
//             "compute",
//             "concern",
//             "condition",
//             "confer",
//             "consider",
//             "consult",
//             "contact",
//             "continue",
//             "contract",
//             "control",
//             "converse",
//             "cook",
//             "copy",
//             "corner",
//             "correct",
//             "cost",
//             "could",
//             "council",
//             "count",
//             "country",
//             "county",
//             "couple",
//             "course",
//             "court",
//             "cover",
//             "create",
//             "cross",
//             "cup",
//             "current",
//             "cut",
//             "dad",
//             "danger",
//             "date",
//             "day",
//             "dead",
//             "deal",
//             "dear",
//             "debate",
//             "decide",
//             "decision",
//             "deep",
//             "definite",
//             "degree",
//             "department",
//             "depend",
//             "describe",
//             "design",
//             "detail",
//             "develop",
//             "die",
//             "difference",
//             "difficult",
//             "dinner",
//             "direct",
//             "discuss",
//             "district",
//             "divide",
//             "do",
//             "doctor",
//             "document",
//             "dog",
//             "door",
//             "double",
//             "doubt",
//             "down",
//             "draw",
//             "dress",
//             "drink",
//             "drive",
//             "drop",
//             "dry",
//             "due",
//             "during",
//             "each",
//             "early",
//             "east",
//             "easy",
//             "eat",
//             "economy",
//             "educate",
//             "effect",
//             "egg",
//             "eight",
//             "either",
//             "elect",
//             "electric",
//             "eleven",
//             "else",
//             "employ",
//             "encourage",
//             "end",
//             "engine",
//             "english",
//             "enjoy",
//             "enough",
//             "enter",
//             "environment",
//             "equal",
//             "especial",
//             "europe",
//             "even",
//             "evening",
//             "ever",
//             "every",
//             "evidence",
//             "exact",
//             "example",
//             "except",
//             "excuse",
//             "exercise",
//             "exist",
//             "expect",
//             "expense",
//             "experience",
//             "explain",
//             "express",
//             "extra",
//             "eye",
//             "face",
//             "fact",
//             "fair",
//             "fall",
//             "family",
//             "far",
//             "farm",
//             "fast",
//             "father",
//             "favour",
//             "feed",
//             "feel",
//             "few",
//             "field",
//             "fight",
//             "figure",
//             "file",
//             "fill",
//             "film",
//             "final",
//             "finance",
//             "find",
//             "fine",
//             "finish",
//             "fire",
//             "first",
//             "fish",
//             "fit",
//             "five",
//             "flat",
//             "floor",
//             "fly",
//             "follow",
//             "food",
//             "foot",
//             "for",
//             "force",
//             "forget",
//             "form",
//             "fortune",
//             "forward",
//             "four",
//             "france",
//             "free",
//             "friday",
//             "friend",
//             "from",
//             "front",
//             "full",
//             "fun",
//             "function",
//             "fund",
//             "further",
//             "future",
//             "game",
//             "garden",
//             "gas",
//             "general",
//             "germany",
//             "get",
//             "girl",
//             "give",
//             "glass",
//             "go",
//             "god",
//             "good",
//             "goodbye",
//             "govern",
//             "grand",
//             "grant",
//             "great",
//             "green",
//             "ground",
//             "group",
//             "grow",
//             "guess",
//             "guy",
//             "hair",
//             "half",
//             "hall",
//             "hand",
//             "hang",
//             "happen",
//             "happy",
//             "hard",
//             "hate",
//             "have",
//             "he",
//             "head",
//             "health",
//             "hear",
//             "heart",
//             "heat",
//             "heavy",
//             "hell",
//             "help",
//             "here",
//             "high",
//             "history",
//             "hit",
//             "hold",
//             "holiday",
//             "home",
//             "honest",
//             "hope",
//             "horse",
//             "hospital",
//             "hot",
//             "hour",
//             "house",
//             "how",
//             "however",
//             "hullo",
//             "hundred",
//             "husband",
//             "idea",
//             "identify",
//             "if",
//             "imagine",
//             "important",
//             "improve",
//             "in",
//             "include",
//             "income",
//             "increase",
//             "indeed",
//             "individual",
//             "industry",
//             "inform",
//             "inside",
//             "instead",
//             "insure",
//             "interest",
//             "into",
//             "introduce",
//             "invest",
//             "involve",
//             "issue",
//             "it",
//             "item",
//             "jesus",
//             "job",
//             "join",
//             "judge",
//             "jump",
//             "just",
//             "keep",
//             "key",
//             "kid",
//             "kill",
//             "kind",
//             "king",
//             "kitchen",
//             "knock",
//             "know",
//             "labour",
//             "lad",
//             "lady",
//             "land",
//             "language",
//             "large",
//             "last",
//             "late",
//             "laugh",
//             "law",
//             "lay",
//             "lead",
//             "learn",
//             "leave",
//             "left",
//             "leg",
//             "less",
//             "let",
//             "letter",
//             "level",
//             "lie",
//             "life",
//             "light",
//             "like",
//             "likely",
//             "limit",
//             "line",
//             "link",
//             "list",
//             "listen",
//             "little",
//             "live",
//             "load",
//             "local",
//             "lock",
//             "london",
//             "long",
//             "look",
//             "lord",
//             "lose",
//             "lot",
//             "love",
//             "low",
//             "luck",
//             "lunch",
//             "machine",
//             "main",
//             "major",
//             "make",
//             "man",
//             "manage",
//             "many",
//             "mark",
//             "market",
//             "marry",
//             "match",
//             "matter",
//             "may",
//             "maybe",
//             "mean",
//             "meaning",
//             "measure",
//             "meet",
//             "member",
//             "mention",
//             "middle",
//             "might",
//             "mile",
//             "milk",
//             "million",
//             "mind",
//             "minister",
//             "minus",
//             "minute",
//             "miss",
//             "mister",
//             "moment",
//             "monday",
//             "money",
//             "month",
//             "more",
//             "morning",
//             "most",
//             "mother",
//             "motion",
//             "move",
//             "mrs",
//             "much",
//             "music",
//             "must",
//             "name",
//             "nation",
//             "nature",
//             "near",
//             "necessary",
//             "need",
//             "never",
//             "new",
//             "news",
//             "next",
//             "nice",
//             "night",
//             "nine",
//             "no",
//             "non",
//             "none",
//             "normal",
//             "north",
//             "not",
//             "note",
//             "notice",
//             "now",
//             "number",
//             "obvious",
//             "occasion",
//             "odd",
//             "of",
//             "off",
//             "offer",
//             "office",
//             "often",
//             "okay",
//             "old",
//             "on",
//             "once",
//             "one",
//             "only",
//             "open",
//             "operate",
//             "opportunity",
//             "oppose",
//             "or",
//             "order",
//             "organize",
//             "original",
//             "other",
//             "otherwise",
//             "ought",
//             "out",
//             "over",
//             "own",
//             "pack",
//             "page",
//             "paint",
//             "pair",
//             "paper",
//             "paragraph",
//             "pardon",
//             "parent",
//             "park",
//             "part",
//             "particular",
//             "party",
//             "pass",
//             "past",
//             "pay",
//             "pence",
//             "pension",
//             "people",
//             "per",
//             "percent",
//             "perfect",
//             "perhaps",
//             "period",
//             "person",
//             "photograph",
//             "pick",
//             "picture",
//             "piece",
//             "place",
//             "plan",
//             "play",
//             "please",
//             "plus",
//             "point",
//             "police",
//             "policy",
//             "politic",
//             "poor",
//             "position",
//             "positive",
//             "possible",
//             "post",
//             "pound",
//             "power",
//             "practise",
//             "prepare",
//             "present",
//             "press",
//             "pressure",
//             "presume",
//             "pretty",
//             "previous",
//             "price",
//             "print",
//             "private",
//             "probable",
//             "problem",
//             "proceed",
//             "process",
//             "produce",
//             "product",
//             "programme",
//             "project",
//             "proper",
//             "propose",
//             "protect",
//             "provide",
//             "public",
//             "pull",
//             "purpose",
//             "push",
//             "put",
//             "quality",
//             "quarter",
//             "question",
//             "quick",
//             "quid",
//             "quiet",
//             "quite",
//             "radio",
//             "rail",
//             "raise",
//             "range",
//             "rate",
//             "rather",
//             "read",
//             "ready",
//             "real",
//             "realise",
//             "really",
//             "reason",
//             "receive",
//             "recent",
//             "reckon",
//             "recognize",
//             "recommend",
//             "record",
//             "red",
//             "reduce",
//             "refer",
//             "regard",
//             "region",
//             "relation",
//             "remember",
//             "report",
//             "represent",
//             "require",
//             "research",
//             "resource",
//             "respect",
//             "responsible",
//             "rest",
//             "result",
//             "return",
//             "rid",
//             "right",
//             "ring",
//             "rise",
//             "road",
//             "role",
//             "roll",
//             "room",
//             "round",
//             "rule",
//             "run",
//             "safe",
//             "sale",
//             "same",
//             "saturday",
//             "save",
//             "say",
//             "scheme",
//             "school",
//             "science",
//             "score",
//             "scotland",
//             "seat",
//             "second",
//             "secretary",
//             "section",
//             "secure",
//             "see",
//             "seem",
//             "self",
//             "sell",
//             "send",
//             "sense",
//             "separate",
//             "serious",
//             "serve",
//             "service",
//             "set",
//             "settle",
//             "seven",
//             "shall",
//             "share",
//             "she",
//             "sheet",
//             "shoe",
//             "shoot",
//             "shop",
//             "short",
//             "should",
//             "show",
//             "shut",
//             "sick",
//             "side",
//             "sign",
//             "similar",
//             "simple",
//             "since",
//             "sing",
//             "single",
//             "sir",
//             "sister",
//             "sit",
//             "site",
//             "situate",
//             "six",
//             "size",
//             "sleep",
//             "slight",
//             "slow",
//             "small",
//             "smoke",
//             "so",
//             "social",
//             "society",
//             "some",
//             "son",
//             "soon",
//             "sorry",
//             "sort",
//             "sound",
//             "south",
//             "space",
//             "speak",
//             "special",
//             "specific",
//             "speed",
//             "spell",
//             "spend",
//             "square",
//             "staff",
//             "stage",
//             "stairs",
//             "stand",
//             "standard",
//             "start",
//             "state",
//             "station",
//             "stay",
//             "step",
//             "stick",
//             "still",
//             "stop",
//             "story",
//             "straight",
//             "strategy",
//             "street",
//             "strike",
//             "strong",
//             "structure",
//             "student",
//             "study",
//             "stuff",
//             "stupid",
//             "subject",
//             "succeed",
//             "such",
//             "sudden",
//             "suggest",
//             "suit",
//             "summer",
//             "sun",
//             "sunday",
//             "supply",
//             "support",
//             "suppose",
//             "sure",
//             "surprise",
//             "switch",
//             "system",
//             "table",
//             "take",
//             "talk",
//             "tape",
//             "tax",
//             "tea",
//             "teach",
//             "team",
//             "telephone",
//             "television",
//             "tell",
//             "ten",
//             "tend",
//             "term",
//             "terrible",
//             "test",
//             "than",
//             "thank",
//             "the",
//             "then",
//             "there",
//             "therefore",
//             "they",
//             "thing",
//             "think",
//             "thirteen",
//             "thirty",
//             "this",
//             "thou",
//             "though",
//             "thousand",
//             "three",
//             "through",
//             "throw",
//             "thursday",
//             "tie",
//             "time",
//             "to",
//             "today",
//             "together",
//             "tomorrow",
//             "tonight",
//             "too",
//             "top",
//             "total",
//             "touch",
//             "toward",
//             "town",
//             "trade",
//             "traffic",
//             "train",
//             "transport",
//             "travel",
//             "treat",
//             "tree",
//             "trouble",
//             "true",
//             "trust",
//             "try",
//             "tuesday",
//             "turn",
//             "twelve",
//             "twenty",
//             "two",
//             "type",
//             "under",
//             "understand",
//             "union",
//             "unit",
//             "unite",
//             "university",
//             "unless",
//             "until",
//             "up",
//             "upon",
//             "use",
//             "usual",
//             "value",
//             "various",
//             "very",
//             "video",
//             "view",
//             "village",
//             "visit",
//             "vote",
//             "wage",
//             "wait",
//             "walk",
//             "wall",
//             "want",
//             "war",
//             "warm",
//             "wash",
//             "waste",
//             "watch",
//             "water",
//             "way",
//             "we",
//             "wear",
//             "wednesday",
//             "wee",
//             "week",
//             "weigh",
//             "welcome",
//             "well",
//             "west",
//             "what",
//             "when",
//             "where",
//             "whether",
//             "which",
//             "while",
//             "white",
//             "who",
//             "whole",
//             "why",
//             "wide",
//             "wife",
//             "will",
//             "win",
//             "wind",
//             "window",
//             "wish",
//             "with",
//             "within",
//             "without",
//             "woman",
//             "wonder",
//             "wood",
//             "word",
//             "work",
//             "world",
//             "worry",
//             "worse",
//             "worth",
//             "would",
//             "write",
//             "wrong",
//             "year",
//             "yes",
//             "yesterday",
//             "yet",
//             "you",
//             "young",
//       ],
// };

const x = async () => {
      await wordsModel.deleteMany({});
      const newWords = new wordsModel({
            language: "english",
            words: commonWords,
            options: [
                  {
                        name: "english 1-100",
                        wordsSlices: [[0, 99]],
                  },
                  {
                        name: "english 101-200",
                        wordsSlices: [[100, 199]],
                  },
                  {
                        name: "english 201-300",
                        wordsSlices: [[200, 299]],
                  },
                  {
                        name: "english 1-300",
                        wordsSlices: [[0, 299]],
                  },
                  {
                        name: "english (1-60 words + all numbers(1-30))",
                        wordsSlices: [
                              [0, 59],
                              [300, 329],
                        ],
                  },
                  {
                        name: "english (all numbers(1-30))",
                        wordsSlices: [[300, 329]],
                  },
                  {
                        name: "english (1-40 words + all special characters(1-20))",
                        wordsSlices: [
                              [0, 39],
                              [330, 349],
                        ],
                  },
                  {
                        name: "english (1-300 words + all special characters(1-20))",
                        wordsSlices: [
                              [0, 299],
                              [330, 349],
                        ],
                  },
                  {
                        name: "english (1-300 words + all numbers(1-30))",
                        wordsSlices: [
                              [0, 299],
                              [300, 329],
                        ],
                  },
                  {
                        name: "english (1-300 words + all numbers(1-30) + all special characters(1-20))",
                        wordsSlices: [
                              [0, 299],
                              [300, 329],
                              [330, 349],
                        ],
                  },
            ],
      });

      await newWords.save();

      //   const newWordsOne = new wordsModel({
      //         language: "javascript",
      //         words: javascript,
      //         options: [
      //               {
      //                     name: "javascript 1-100",
      //                     wordsSlices: [[0, 99]],
      //               },
      //         ],
      //   });

      //   await newWordsOne.save();
};

x();

// const numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
// const newNumbers = [];

// for (let i = 0; i < 50; i++) {}

// let two = [85, 70, 26, 49, 31, 94, 36, 58, 10, 27];
// let three = [182, 693, 547, 476, 319, 208, 706, 543, 928, 134];
// let four = [7036, 2518, 9485, 2173, 9460, 9134, 8072, 6580, 2693, 4715];
// let allNumbers = [
//       85, 70, 26, 49, 31, 94, 36, 58, 10, 27, 182, 693, 547, 476, 319, 208, 706,
//       543, 928, 134, 7036, 2518, 9485, 2173, 9460, 9134, 8072, 6580, 2693, 4715,
// ];

let allSpecialCharacters = [
      "~",
      "@",
      "#",
      "$",
      "%",
      "^",
      "&",
      "*",
      "(",
      ")",
      "_",
      "+",
      "{",
      "}",
      "|",
      ":",
      '"',
      "?",
      ">",
      "<",
];
